### ISSUE TITLE
Error Popup when Copy ID Is Clicked

### ISSUE THREAD

**Issue by chez14** [garoose/copy-message-id#10]
Hi `garoose`, Thanks for the wholesome add-on.

I got a problem when i clicked the Copy ID button. When clicked, it give me a red tooltip-like popups with message:

> Failed to copy message ID: Error: Invalid mail tab ID: 8

Thanks!

- Thunderbird: 68.8.0 (64-bit)
- OS: Ubuntu 18.04.4 LTS (bionic)

**Comment by garoose** [comment]
Hm sorry about that. I managed to track the issue down to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1525558) bug, I'll look into solutions. It's an issue with getting the message ID of a message brought up in its own tab, so if you copy it from the 3-pane view it should work as a work-around for now.

**Comment by chez14** [comment]
Ahhh i see. Thank you for the trick! So all i have to do now is wait for new patch release, co..rrect?

**Comment by garoose** [comment]
Yep!
