### ISSUE TITLE
Add a way to use a newline character as the "Suffix"

### ISSUE THREAD

**Issue by ghost** [garoose/copy-message-id#13]
I don't know how to copy final newline character after the message ID string. Could you make it possible to use `\n` or `\\n` in the Suffix field and interpret it when copying to clipboard?

Thank you!

[As for my use case: I discovered this add-on after trying to find a way to manually fix mailing list threading for mails coming from Outlook users (as Outlook omits a required header). I discovered that the Header Tools Lite add-on can edit mails to add a new header. The message ID value is exactly what I need to fix threading, and this add-on also allows including a prefix, so I can even add `In-reply-to: ` for my header name. But I'd really like to remove the additional step of having to add a newline manually.]

**Comment by garoose** [comment]
Sorry this took me so long to get to. I've developed a solution and am working on a release. Thanks for your patience and I hope it will still be useful to you.

**Comment by ghost** [comment]
Absolutely no reason to apologize -- Thanks a lot! This sounds great.

Iiuc, your patch allows just typing plain newlines?

**Comment by garoose** [comment]
> Absolutely no reason to apologize -- Thanks a lot! This sounds great.
> 
> Iiuc, your patch allows just typing plain newlines?

Yep that's right! Just hit Enter in the `suffix` field. Let me know if you have any problems.

**Comment by ghost** [comment]
I didn't realize this was published already -- I tried it this morning and the new add-on version was already installed and it works flawlessly. Thanks a lot (again)!
