### ISSUE TITLE
Suggestion: Have config to choose betwen copy "only the message ID value" vs "the full-header"

### ISSUE THREAD

**Issue by xmontero** [garoose/copy-message-id#3]
Hi, Joshua!

I just discovered your extension today and that's exactly what I was looking for during years!

I see that when you click, it puts in the clipboard the **value** of the Message-ID. For example in this header:

    Message-ID: <123456789@some-sender>

the result is to have in the clipboard the string `"123456789@some-sender"`

I have been using the message ID (copying it manually!!) for my CRM entries. For example this could be a regular entry of our everyday usage:

    - Phoned John to 5555555.
    - Answered Voice Mail.
    - Requested tariff by email.
    - Received email with Message-ID: <123456789@some-sender>
    - Received 2 PDFs in the email, the second is corrupt.

I do add the full header, so later on it is easy to scan with regular expressions the full database and find "where emails are referenced" as the structure `*Message-ID: <*>` is not used manually by anyone writing in the CRM.

I wonder (I may help if you direct me, open to contribute) if we could have a "config option" so you set if you want to copy "the value" or "the full header".

In the case of full header we'd end having `"Message-ID: <123456789@some-sender>"` in the clipboard.

I've never coded an extension for thunderbird (nor firefox), but I'm a coder anyway so I'm open to help if you give me the starting point :D

In any case, CONGRATS for your contribution to the world! And thanks!

**Comment by garoose** [comment]
Hey thanks for your kind words. I was inspired by your request and decided to ad prefix/suffix configuration options. If you're able, can you test the changes for me and see if it solves your issue?
See the pull request here #4.

**Comment by xmontero** [comment]
In relation to https://github.com/garoose/copy-message-id/pull/4#issuecomment-626593415 would you suggest any forum where to discuss about this with other addon-creator folks?

**Comment by garoose** [comment]
Sorry I haven't really found a community of add-on developers. I mostly got my answers directly from the documentation and example add-ons.

Oh here's a Mozilla add-ons forum actually: https://discourse.mozilla.org/c/add-ons

**Comment by xmontero** [comment]
Okey, so... I think we can do it but for simplicity, do not support some cases that "might" happen but most probably will not.

Let's begin...

How to get the "original headers"
====================

According to here https://thunderbird-webextensions.readthedocs.io/en/68/messages.html there's a new function from 68+ version which is `getRaw()`.

The function returns a promise fullfilled with a string which is the unmodified message as stored in the mail server.

I tested the function in the thunderbird console:

![imagen](https://user-images.githubusercontent.com/5641621/81742459-6fd30500-94a0-11ea-9a92-374366885bc9.png)

1) I set a breakpoint in the debugger just before the `.getFull()`
2) I click on the "Copy Message ID" button and I get the debugger paused just there.

Then, I switch to the console:

I just call `.getFull()` and assign the result to a variable, which (as defined) is a promise and -as natural- will be in the "pending" state immediately after:

![imagen](https://user-images.githubusercontent.com/5641621/81742675-c80a0700-94a0-11ea-8aa9-4d0c751d2289.png)

Then I just re-print the promise, and et-voilà: I can see the original raw message in the console:

![imagen](https://user-images.githubusercontent.com/5641621/81743007-3fd83180-94a1-11ea-81c2-4a3a6279ef2d.png)

From here on, how to parse the text
======================

1. We may find a blank line to separate the "header section" from the "body section". https://tools.ietf.org/html/rfc5322#section-2.1
1. In the headers section, according to the table here https://tools.ietf.org/html/rfc5322#section-3.6 `message-id` can appear 0 or 1 times, although it *should* be there and it is expected that typically at least one exists, as explained here https://tools.ietf.org/html/rfc5322#section-3.6.4
1. As per this section, https://tools.ietf.org/html/rfc5322#section-3.6.4 the "Message-ID" belongs to the group "Identification Fields", is a "structured field" and -as any other field- is subject to the folding described here: https://tools.ietf.org/html/rfc5322#section-2.2.3
1. In particular this section https://tools.ietf.org/html/rfc5322#section-3.2.2 defines that the structured messages may appear with comments, which introduce white spacing subject to optional folding.

This means that all of there message Ids are correct:

    Message-ID: <hello@someserver>
    Next-Header: some thing

    Message-ID: <hello@someserver> (nice day (tomorrow and yesterday))
    Next-Header: some thing

    Message-ID: <hello@someserver> (nice
     day (tomorrow and yesterday))
    Next-Header: some thing

Then....

* If we get the full message
* Search for the "blank line" and discard the blank line itself and the rest, what we keep is exactly the "headers section".
* We may then scan line by line, seeking insensitively `Message-ID:` and get the full line.
* Then, scan the next line.
    * If it does start with a space, copy the line right after the previous one.
    * Repeat scanning next line, until the next line starts with a label right to the beginning of the line, this means the start of another header.

To simplify
=======

All the previous seems too much complexity for a case that is not going to be maybe with a very low probability.

I'd say that most probably for a first version, we could cope with the following:

Happy Path:
-------------

* The Message-ID occurs exactly once, and is **not** folded. In addition, in trying to follow the Postel's Law https://devopedia.org/postel-s-law we will cope with case-insensitive key for the field.

Sad Path:
---------

* The Message-ID does not occur => Throw exception "Message-ID not found"
* The Message-ID is folded => Throw exception "Folded Message-ID is unsupported"
* The Message-ID occurs multiple times => Throw exception "Multiple Message-ID found"

To do so, I'd bet for this simple forward-only simple scanning (in pseudocode):

    Read the raw text

    Init some vars:
        MessageIdFoundTimes = 0
        MessageIdFolded = false
        MessageIdLine = null
        ScanningTheNextLine = false

    For each line, loop until break
        If the line matches `/^(message-id:)/i` (`i` for insensitive) then
            // Found a new Message-ID header
            MessageIdFoundTimes++
            MessageIdLine = the found line
            ScanningTheNextLine = true
        Else if ( ScanningTheNextLine )
            ScanningTheNextLine = false
            If the line does not match `/^[a-z]/i` then
                // The line just after a Message-ID header is not a label. Assume folded.
                MessageIdFolded = true
        Else if the line is blank then
            // We reached the end of headers
            Break the loop

    If MessageIdFoundTimes = 0
        Throw not found
    If MessageIdFoundTimes = 0
        Throw too many
    If MessageIdFolded
        Throw format not yet supported

    Return MessageIdLine

The exceptions could send a message-box or some kind of alert to the user.

I think this could work.

Hypotheses:
- 0 times will probably never happen.
- 2+ times will probably never happen.
- Folded will unlikely happen, but if it happens, the user will see "not copied".

This copy mode could have a configuration checkbox saying "Get raw header line".
If true, getRaw() and do this. If false (default classic mode) getFull and process normally.
I'd bet for keeping prefix and suffix "after" any of those processings, so it the raw line is:

    MeSsAgE-iD: <hello@somesender>

You still could have this in the clipboard if you need for any silly reason:

    # Imagine we want to enclose this in an XML tag:
    # Prefix = "<raw-header>"
    # Suffix = "</raw-header>"
    <raw-header>MeSsAgE-iD: <hello@somesender></raw-header>

Here, ready to help.

**Comment by garoose** [comment]
Excellent findings, I can take a implementing that soon.

**Comment by garoose** [comment]
See the new PR I opened, it copies the whole message ID and does handle multiline IDs (mostly cause I noticed one in my mailbox). It even maintains most of the whitespace from the ID, only trimming from the end.

**Comment by xmontero** [comment]
Will try... gimme a few days to release accumulated work and then I will do!

**Comment by garoose** [comment]
I think we can close this out now that #5 is merged, feel free to re-open if I was mistaken.
