### ISSUE TITLE
Provide visual feedback when copy has been completed

### ISSUE THREAD

**Issue by xmontero** [garoose/copy-message-id#8]
Sometimes when software has a "copy" function, it provides a visual feedback that something has been copied to the clipboard.

Here are a few examples:

In a private admin panel
-------------------------
When you  copy, you get a visual "tag" plus a cross-line saying "you aready got this one".
![imagen](https://user-images.githubusercontent.com/5641621/82211792-b47ff580-9911-11ea-8f46-6de9b8274e29.png)

In StackOverflow
-----------------
When copying a permalink, there's a popup global to the web page.
![imagen](https://user-images.githubusercontent.com/5641621/82211884-e3966700-9911-11ea-9478-4c49777c2f1d.png)

In Gitlab
---------
When you copy a commit hash, there's a balloon as a "tooltip"
![imagen](https://user-images.githubusercontent.com/5641621/82212187-6d463480-9912-11ea-882e-5cb6d5bb0123.png)

In Youtube 
-----------
When you share and "copy the link" there's an animated circle indicating visual "in-place" feedback with a moving shape.
![imagen](https://user-images.githubusercontent.com/5641621/82212515-f52c3e80-9912-11ea-9508-fa5d7a39ff7e.png)

Common to all of them are two facts:

a) They are "visually very easy to recognize"
b) There's no additional click needed by the user (ie: it's non-interrupting the user flow).

I don't know what options we have in the API.

- If we can force tooltips to show, that could be the easiest solution. Just display "Copied" besides.
- If we don't have tooltips, maybe we could play with the color of the button: Make it green, start a timer to 200ms, on timeout revert to the "default" color.

If we find a solution to this, we could also signal the exception in #7 with an alternative display. For example tooltip "Exception, could not copy" or if we go for the color solution, make it blink in red. In this case this would not be a substitute of the message box, as the exception does really need a user interaction to ensure the user saw it and did not escape to his mind.

Whatever the solution, the visual feedback should be placed in code *after* the placement into the clipboard has succeeded.

**Comment by garoose** [comment]
Initial test into popup display lol

![youcopiedit](https://user-images.githubusercontent.com/3311849/82402034-70801400-9a29-11ea-9a9d-f6b4ecb08eae.png)
